---
- name: Initialise System
  hosts: localhost
  gather_facts: true
  vars:
      system: '{{ ansible_facts["os_family"] }}'
  tasks:
    - name: Debug System Variable
      debug:
        var: system

    - name: Darwin Setup
      when: system == "Darwin"
      block:
        - name: Install macOS Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - mas
              - neovim
        
        - name: Install Cask Apps 
          community.general.homebrew_cask:
            name: "{{ item }}"
            state: present
          with_items:
            - gitfox
            - hyperkey
            - iterm2
            - kitty
            - orbstack
            - osu
            - swish
            - texifier
            - wezterm
              
        - name: Install & Upgrade App Store Apps
          community.general.mas:
            id: # - 424390742  # Compressor - 424389933  # Final Cut Pro - 634148309 # Logic Pro - 634159523 # MainStage - 434290957 # Motion - 1289583905 # Pixelmator Pro - 497799835 # Xcode
              - 1436953057 # Ghostery
              - 1571998974 # Mastodon
              - 1521432881 # Session
            state: present
            upgrade_all: true

    - name: Linux Setup
      when: system == "Linux"
      become: true
      block:
        - name: Install Linux Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - autotiling
              - fd
              - foot
              - git
              - grim
              - keyd
              - neovim
              - nerdfonts
              - ripgrep
              - sd
              - sioyek
              - slurp
              - swayfx
              - swayidle
              - swaylock

    - name: Universal Setup
      block:
        - name: Configure Git User Name
          community.general.git_config:
            name: user.name
            value: "Mac"
            
        - name: Configure Git Email Address
          community.general.git_config:
            name: user.email
            value: "maclong9@icloud.com"
