---
- name: Initialise System
  hosts: localhost
  gather_facts: true
  vars:
      system: '{{ ansible_facts["os_family"] }}'
  tasks:
    - name: Debug System Variable
      debug:
        var: system

    - name: Darwin Setup
      when: system == "Darwin"
      block:
        - name: Install macOS Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - github
              - hyperkey
              - mactex
              - mas
              - neovim
              - orbstack
              - sioyek
              - swish
              - warp
              
        - name: Install & Upgrade App Store Apps
          community.general.mas:
            id:
            # - 424390742 # Compressor
            # - 424389933 # Final Cut Pro
            # - 634148309 # Logic Pro
            # - 634159523 # MainStage
            # - 434290957 # Motion
              - 497799835 # Xcode
            # - 1289583905 # Pixelmator Pro
            state: present
            upgrade_all: true

    - name: Linux Setup
      when: system == "Linux"
      become: true
      block:
        - name: Install Linux Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - autotiling
              - fd
              - foot
              - git
              - grim
              - keyd
              - neovim
              - nerdfonts
              - ripgrep
              - sd
              - sioyek
              - slurp
              - swayfx
              - swayidle
              - swaylock
              - toolbox

    - name: Setup AstroNvim
      block:
      - name: Clone Astronvim Repository
        git:
          repo: https://github.com/Astronvim/astronvim.git
          dest: ~/.config/nvim
  
      - name: Create User Configuration Directory
        file:
          path: ~/.config/nvim/lua/user
          state: directory
  
      - name: Create symlink for astro.lua to init.lua
        file:
          src: ~/.config/astro.lua
          dest: ~/.config/nvim/lua/user/init.lua
          state: link

