---
- name: Initialise System
  hosts: localhost
  gather_facts: true
  vars:
      system: '{{ ansible_facts["os_family"] }}'
  tasks:
    - name: Debug System Variable
      debug:
        var: system

    - name: Darwin Specific Setup
      when: system == "Darwin"
      block:
        - name: Install macOS Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - alacritty
              - github
              - hyperkey
              - mactex
              - mas
              - neovim
              - orbstack
              - sioyek
              - swish
              
        - name: Install & Upgrade App Store Apps
          community.general.mas:
            id:
              - 409183694 # Keynote
              - 413857545 # Divvy
            state: present
            upgrade_all: true



    - name: Linux Specific Setup
      when: system == "Linux"
      become: true
      block:
        - name: Install Linux Tools
          ansible.builtin.package:
              name: "{{ item }}"
              state: present
          with_items:
              - alacritty
              - aylurs-gtk-shell
              - fd
              - gh
              - git
              - grim
              - hyprland
              - keyd
              - neovim
              - ripgrep
              - sd
              - sioyek
              - slurp
              - toolbox
              - unzip
              - zsh

        - name: Set Default Shell to ZSH
          user:
              name: "mac"
              shell: /bin/zsh

        - name: Ensure Font Directory Exists
          ansible.builtin.file:
              path: /usr/local/share/fonts
              state: directory
              mode: '0755'

        - name: Create .zprofile File
          ansible.builtin.copy:
              content: |
                  eval "$(atuin)"
              dest: ~/.zprofile
              mode: '0644'

        - name: Fetch CascadiaMono Nerd Font
          ansible.builtin.get_url:
              url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/CascadiaMono.zip
              dest: /usr/local/share/fonts/CascadiaMono.zip
              mode: '0644'

        - name: Unarchive CascadiaMono Nerd Font
          ansible.builtin.unarchive:
              src: /usr/local/share/fonts/CascadiaMono.zip
              dest: /usr/local/share/fonts/
