* Dotfiles 

** Usage

Run the following in any macOS terminal.

#+begin_src sh
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/mac-codes9/dotfiles/main/scripts/install.sh)"
#+end_src

#+BEGIN_QUOTE
Note: If the script fails to run at any point it will clean up the files that were involved in the setup.

Note: Make sure to sign into the App Store before running, otherwise `mas` will not work.

WARNING: This script uses `sudo` mode to install MacPorts. Read the script before running it on your system.
#+END_QUOTE

*** System Explanation
**** Use Cases

- Graphics
- Music Production
- Programming
  - Shell
  - Zig
  - Rust
  - Web
  - Swift
- Project Management
- Video Editing
- Virtualisation 
- Writing

***** Applications 

- Apple Apps
  - Compressor
  - Final Cut Pro
  - Logic Pro
  - MainStage
  - Motion
  - Xcode
- Emacs
  - [Prettier Icon](https://github.com/SavchenkoValeriy/emacs-icons/tree/main)
- HyperKey
- Linear
- Pixelmator Pro
- Safari Extensions
  - Ghostery 


~1436953057 1289583905 1436953057 424390742 424389933 1436953057 1534275760 634148309 634159523 43420957 1289583905 497799835~

***** Tooling

- alacritty
- bun
- fd
- fzf
- github-cli
- mas
- ripgrep
- rust
- sd
- zig
