github.com:
    users:
        maclong9:
            oauth_token: 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
    git_protocol: https
    user: maclong9
    oauth_token: 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
