github.com:
    users:
        maclong9:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: maclong9
