github.com:
    users:
        mac-codes9:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mac-codes9
