github.com:
    users:
        mac-codes9:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mac-codes9
