- name: Install System Tools
  ansible.builtin.package:
    name: '{{ item }}'
  with_items: 
    - mas
    - neovim
    - koekeishiya/formulae/skhd
    - koekeishiya/formulae/yabai
    - zegervdv/zathura/zathura
    - zegervdv/zathur/zathura-pdf-mupdf
  
- name: Install Cask Apps 
  community.general.homebrew_cask:
    name: '{{ item }}'
  with_items: 
    - alacritty
    - element
    - hyperkey
    - orbstack
    - osu
          
- name: Install App Store Apps
  community.general.mas:
    id: '{{ item }}'
  with_items:
  # - 424390742  # Compressor 
  # - 424389933  # Final Cut Pro 
  # - 634148309  # Logic Pro 
  # - 634159523  # MainStage 
  # - 434290957  # Motion 
  # - 497799835  # Xcode
    - 1289583905 # Pixelmator Pro 

  ignore_errors: true

- name: Open Applications for Configuration
  ansible.builtin.command: open -a '{{ item }}'
  with_items:    
    - element
    - hyperkey

- name: Create Directory for Zathura
  ansible.builtin.file: 
    path: $(brew --prefix zathura)/lib/zathura
    state: directory

- name: Link Zathura Plugin
  ansible.builtin.file:
    path: $(brew --prefix zathura-pdf-mupdf)/libpdf-mupdf.dylib 
    dest: $(brew --prefix zathura)/lib/zathura/libpdf-mupdf.dylib
    state: link
