- name: Install Tools
  ansible.builtin.package:
    name: '{{ item }}'
  with_items:
    - deno
    - mas
    
- name: Install Cask Apps 
  community.general.homebrew_cask:
    name: '{{ item }}'
  with_items: 
    - alacritty
    - element
    - hyperkey
    - orbstack
    - osu
    - texifier
          
- name: Install App Store Apps
  community.general.mas:
    id: '{{ item }}'
  with_items:
  # - 424390742  # Compressor 
  # - 424389933  # Final Cut Pro 
  # - 634148309  # Logic Pro 
  # - 634159523  # MainStage 
  # - 434290957  # Motion 
  # - 497799835  # Xcode
    - 1289583905 # Pixelmator Pro 

- name: Open Applications for Configuration
  ansible.builtin.command: open -a '{{ item }}'
  with_items:    
    - element
    - hyperkey

- name: Symlink Vim Configuration
  ansible.builtin.file:
    src: ~/.config/vimrc
    dest: ~/.vimrc
    state: link
