- name: Darwin Setup
  when: system == 'Darwin'
  block:
    - name: Install System Tools
      ansible.builtin.package:
        name: '{{ item }}'
      with_items: '{{ darwin.tools }}'
      
    - name: Install Cask Apps 
      community.general.homebrew_cask:
        name: '{{ item }}'
      with_items: '{{ darwin.casks }}'
              
    - name: Install App Store Apps
      community.general.mas:
        id: '{{ darwin.apps }}'
      ignore_errors: true
