- name: Install System Tools
  ansible.builtin.package:
    name: '{{ item }}'
  with_items: 
    - mas
    - neovim
  
- name: Install Cask Apps 
  community.general.homebrew_cask:
    name: '{{ item }}'
  with_items: 
    - element
    - hyperkey
    - iterm2
    - orbstack
    - osu
    - sioyek
    - swish
    - utm
          
- name: Install App Store Apps
  community.general.mas:
    id: '{{ item }}'
  with_items:
  # - 424390742  # Compressor 
  # - 424389933  # Final Cut Pro 
  # - 634148309  # Logic Pro 
  # - 634159523  # MainStage 
  # - 434290957  # Motion 
  # - 497799835  # Xcode
    - 1289583905 # Pixelmator Pro 

  ignore_errors: true

- name: Open Applications for Configuration
  ansible.builtin.command: open -a '{{ item }}'
  with_items:
    - hyperkey
    - swish
