- name: Universal Setup
  block:
    - name: Set Users Shell to ZSH
      become: yes
      user:
        name: mac
        shell: /bin/zsh

    - name: Link Configuration Files
      file:
        src: "~/.config/{{ item }}"
        dest: "~/.{{ item }}"
        state: link
      with_items:
        - vimrc
        - zshrc
        
    - name: Add cron job for maintenance script
      ansible.builtin.cron:
        name: Run maintenance script
        weekday: "1" 
        hour: "12" 
        minute: "0"
        job: "~/.config/scripts/maintenance.sh"
