- name: Universal Setup
  block:
    - name: Set Users Shell to ZSH
      become: yes
      user:
        name: mac
        shell: /bin/zsh

    - name: Symbolically Link ZSH Configuration
      file:
        src: $HOME/.config/zsh/zshrc
        dest: $HOME/.zshrc
      
    - name: Set up Git aliases
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.command }}"
      loop:
        - { name: "alias.co", command: "commit -m" }
        - { name: "alias.ci", command: "commit" }
        - { name: "alias.pu", command: "push" }
        - { name: "alias.pl", command: "pull" }
        - { name: "alias.plnr", command: "pull --no-rebase" }
        - { name: "alias.st", command: "status" }
        - { name: "alias.lg", command: "log --oneline --decorate --graph" }

    - name: Add cron job for maintenance script
      ansible.builtin.cron:
        name: Run maintenance script
        weekday: "1" 
        hour: "12" 
        job: "{{ ansible_env.HOME }}/.config/scripts/maintenance.sh"
