- name: Install System Tools
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
  with_items:
    - alacritty
    - apparmor
    - brightnessctl
    - cronie
    - curl
    - firefox
    - fzf
    - gammastep
    - git
    - github-cli
    - mako
    - mesa-dri
    - neofetch
    - neovim
    - pipewire
    - seatd
    - swayfx
    - swayidle
    - swaylock
    - tlp
    - unzip
    - wget
    - wl-clipboard
    - zig
    - zsh
  ignore_errors: true

- name: Configure App Armor
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel4 apparmor=1 security=apparmor"'
  ignore_errors: true

- name: Update grub
  become: yes
  shell: update-grub
  ignore_errors: true

- name: Activate tlp Service
  become: true
  file:
    src: /etc/sv/tlp
    dest: /var/service/
    state: link

- name: Activate seatd Service
  become: true
  file:
    src: /etc/sv/seatd
    dest: /var/service

- name: Activate cronie Service
  become: true
  file:
    src: /etc/sv/cronie
    dest: /var/service

- name: Activate gammastep Service
  become: true
  file:
    src: /etc/sv/gammastep
    dest: /var/service

- name: Fetch SFMono Nerd Font
  become: true
  get_url:
    url: https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized/blob/main/LigaSFMonoNerdFont-Regular.otf
    dest: /usr/local/share/fonts/SFMono-Nerd-Font-Ligaturized.otf
