- name: Install System Tools
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
  with_items:
    - alacritty
    - apparmor
    - cronie
    - curl
    - dejavu-fonts-ttf
    - firefox
    - fzf
    - git
    - github-cli
    - grim
    - mako
    - mesa-dri
    - neovim
    - pipewire
    - seatd
    - slurp
    - swayfx
    - tlp
    - unzip
    - wget
    - wl-clipboard
    - zig
    - zsh
  ignore_errors: true

- name: Configure App Armor
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 apparmor=1 security=apparmor"'
  ignore_errors: true

- name: Update grub
  become: yes
  ansible.builtin.shell: update-grub
  ignore_errors: true

- name: Activate tlp Service
  become: true
  ansible.builtin.file:
    src: /etc/sv/tlp
    dest: /var/service/tlp
    state: link

- name: Activate keyd Service
  become: true
  ansible.builtin.file:
    src: /etc/sv/keyd
    dest: /var/service/tlp
    state: link

- name: Activate seatd Service
  become: true
  ansible.builtin.file:
    src: /etc/sv/seatd
    dest: /var/service/seatd
    state: link

- name: Activate dbus Service
  become: true
  ansible.builtin.file:
    src: /etc/sv/dbus
    dest: /var/service/dbus
    state: link

- name: Add User to `_seatd` Group
    user:
      name: mac
      groups: _seatd
      append: yes

- name: Activate cronie Service
  become: true
  ansible.builtin.file:
    src: /etc/sv/cronie
    dest: /var/service/cronie
    state: link

- name: Ensure Font Directory Exists
  become: true
  file:
    path: /usr/local/share/fonts
    state: directory

- name: Fetch SFMono Nerd Font
  become: true
  get_url:
    url: https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized/blob/main/LigaSFMonoNerdFont-Regular.otf
    dest: /usr/local/share/fonts/SFMono-Nerd-Font-Ligaturized.otf
