---
- name: Initialise System
  hosts: localhost
  gather_facts: true
  vars:
    system: '{{ ansible_facts["os_family"] }}'
  vars_files:
    - './packages.yml'
  
  tasks:
    - name: Darwin Setup
      when: system == 'Darwin'
      block:
        - name: Check if Homebrew is Installed
          stat:
            path: /usr/local/bin/brew
          register: brew_installed

        - name: Install Homebrew
          command: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          changed-when: true

        - name: Create .zprofile with Homebrew Reference
          command: echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> "$HOME/.zprofile"
          changed-when: true
          
        - name: Install System Tools
          ansible.builtin.package:
            name: '{{ item }}'
          with_items: '{{ darwin.tools }}'
        
        - name: Install Cask Apps 
          community.general.homebrew_cask:
            name: '{{ item }}'
          with_items: '{{ darwin.casks }}'
              
        - name: Install App Store Apps
          community.general.mas:
            id: '{{ darwin.apps }}'

    - name: Linux Setup
      when: system == 'void'
      become: true
      block:
        - name: Install Linux Tools
          ansible.builtin.package:
            name: '{{ item }}'
          with_items: '{{ linux.tools }}'

        - name: Install Flatpaks
          community.general.flatpak:
            name: '{{ item }}'
          with_items: '{{ linux.flatpak }}'

       # TODO: seperate playbook for install sect, 
       # TODO: apparmor, ntp, tlp, seatd, other river & compile ags
