---
- name: Initialise System
  hosts: localhost
  gather_facts: true
  vars:
    system: '{{ ansible_facts["os_family"] }}'
  vars_files:
    - './packages.yml'
  
  tasks:
    - name: Darwin Setup
      when: system == 'Darwin'
      block:
        - name: Install System Tools
          ansible.builtin.package:
            name: '{{ item }}'
          with_items: '{{ darwin.tools }}'
        
        - name: Install Cask Apps 
          community.general.homebrew_cask:
            name: '{{ item }}'
          with_items: '{{ darwin.casks }}'
              
        - name: Install App Store Apps
          community.general.mas:
            id: '{{ darwin.apps }}'

    - name: Linux Setup
      when: system == 'void'
      block:
        - name: Install Linux Tools
          become: true
          ansible.builtin.package:
            name: '{{ item }}'
          with_items: '{{ linux.tools }}'

        - name: Install Flatpaks
          become: true
          community.general.flatpak:
            name: '{{ item }}'
          with_items: '{{ linux.flatpak }}'

       # TODO: seperate playbook for install sect, apparmor
