- name: Prepare Void Installation Media
  hosts: localhost
  gather_facts: true
  vars:
    base_url: 'https://repo-default.voidlinux.org/live/current'
    version: 'void-live-x86_64-musl-20230628-base.iso'
    dest: '/tmp/void'
    pub_url: 'https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/void-release-keys/files/void-release-20230628.pub'
    system: '{{ ansible_facts["os_family"] }}'
    sudo: '{{ system != "Darwin" }}'
    grep: 'musl-20230628-base.iso sha256sum.txt'
  tasks:
    - name: Setup Utilities
      block:
        - name: Create Temporary Directory for Downloaded Files
          ansible.builtin.file:
            path: '{{ dest }}'
            state: directory
            mode: '0755'

        - name: Install minisign for Verification
          become: "{{ sudo }}"
          ansible.builtin.package:
            name: minisign

        - name: Install sha2 on macOS for Integrity Verification
          when: system == "Darwin"
          ansible.builtin.package:
            name: sha2

    - name: Download ISO & Supporting Files
      block:
        - name: Check for ISO File
          ansible.builtin.stat:
            path: '{{ dest }}/{{ version }}'
          register: iso_stat

        - name: Fetch ISO File
          when: not iso_stat.stat.exists
          ansible.builtin.get_url:
            url: '{{ base_url }}/{{ version }}'
            dest: '{{ dest }}'
            checksum: sha256:c6de5ce00342c40f98f1627fea0e81db9d16b1758c43b0371aa24ee61f08cb45
            mode: '0644'

        - name: Fetch Text Verification
          ansible.builtin.get_url:
            url: '{{ base_url }}/sha256sum.txt'
            dest: '{{ dest }}'
            mode: '0644'

        - name: Fetch Signature
          ansible.builtin.get_url:
            url: '{{ base_url }}/sha256sum.sig'
            dest: '{{ dest }}'
            mode: '0644'

        - name: Fetch Signing Keys
          ansible.builtin.get_url:
            url: '{{ pub_url }}'
            dest: '{{ dest }}'
            mode: '0644'

    - name: Verify Digital Signature
      block:
        - name: Verify Authenticity of `sha256sum.txt`
          ansible.builtin.command: "minisign -V -p {{ dest }}/void-release-20230628.pub -x {{ dest }}/sha256sum.sig -m {{ dest }}/sha256sum.txt"
          register: txt_authenticity
          changed_when: true

        - name: Verify Checksum of Image
          when: system != 'Darwin'
          ansible.builtin.shell: |
            cd {{ dest }}
            shasum -a 256 -c | grep musl-20230628-base.iso sha256sum.txt
          register: image_authenticity
          changed_when: true

        - name: Verify Checksum of Image (macOS)
          when: system == 'Darwin'
          ansible.builtin.shell: |
            cd {{ dest }}
            shasum -a 256 -c | grep '{{ grep }}'
          register: image_authenticity_mac
          changed_when: true
